dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - travis_ci
notifications:
  email:
    recipients:
      - sunil@ost.com
    on_success: always
    on_failure: always
node_js:
  - "8"
  - "7"
# Create a Travis memcached enabled environment
services: memcache
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
install:
  - npm install
# Start memcached instances on localhost
before_script:
   - memcached -p 11212 -d
   - memcached -p 11213 -d
script:
   - node test/test.js

after_script:
